# Generated by Django 6.0.3 on 2026-04-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Автоматически обновляется при изменении курса или его уроков",
                verbose_name="Дата последнего обновления",
            ),
        ),
    ]
