# Generated by Django 6.0.3 on 2026-04-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_course_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notification_sent",
            field=models.DateTimeField(
                blank=True,
                help_text="Время последней отправки уведомления подписчикам",
                null=True,
                verbose_name="Дата последнего уведомления",
            ),
        ),
    ]
